- name: Wireguard Docker Container
  docker_container:
    name: wireguard
    image: ghcr.io/linuxserver/wireguard
    pull: true
    volumes:
	  - "{{ docker_home }}/wireguard/config:/config"
	  - "/lib/modules:/lib/modules"
    ports:
      - "51820:51820/udp"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "1000"
      PGID: "1000"
	  SERVERURL: "{{ ansible_nas_domain }}"
      SERVERPORT: "51820" #optional
      PEERS: "andrewPhone, andrewLaptop" #optional
      PEERDNS: "1.1.1.1" #optional
      INTERNAL_SUBNET: "10.2.6.0" #optional
      ALLOWEDIPS: "0.0.0.0/0" #optional
	sysctls:
	  net.ipv4.conf.all.src_valid_mark: "1"
	capabilities:
	  - net_admin
	  - sys_module
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "wireguard"
      traefik.frontend.rule: "Host:wireguard.{{ ansible_nas_domain }}"
      traefik.enable: "{{ wireguard_available_externally }}"
      traefik.port: "51820"
